" let g:pathogen_disabled = []
" call add(g:pathogen_disabled, 'Python-Syntax-Folding')
" call add(g:pathogen_disabled, 'The-NERD-tree')
" call add(g:pathogen_disabled, 'minibufexpl.vim')
" "call add(g:pathogen_disabled, 'IndentAnything')
" "call add(g:pathogen_disabled, 'ack.vim')
" "call add(g:pathogen_disabled, 'bufexpl.vim')
" "call add(g:pathogen_disabled, 'dbext.vim')
" "call add(g:pathogen_disabled, 'netrw.vim')
" "call add(g:pathogen_disabled, 'pyflakes-vim')
" "call add(g:pathogen_disabled, 'pylint.vim')
" "call add(g:pathogen_disabled, 'python.vim')
" "call add(g:pathogen_disabled, 'python_match.vim')
" "call add(g:pathogen_disabled, 'pythoncomplete')
" "call add(g:pathogen_disabled, 'pythonEditing.vim')
" "call add(g:pathogen_disabled, 'taglist.vim')
" "call add(g:pathogen_disabled, 'vim-abolish')
" "call add(g:pathogen_disabled, 'vim-bundler')
" "call add(g:pathogen_disabled, 'vim-colors-solarized')
" "call add(g:pathogen_disabled, 'vim-fugitive')
" "call add(g:pathogen_disabled, 'vim-javascript')
" "call add(g:pathogen_disabled, 'vim-jquery')
" "call add(g:pathogen_disabled, 'vim-less')
" "call add(g:pathogen_disabled, 'vim-rails')
" "call add(g:pathogen_disabled, 'vim-rake')
" "call add(g:pathogen_disabled, 'vim-surround')
" call pathogen#runtime_append_all_bundles()
" "call pathogen#infect()
" "call pathogen#helptags()
